.Dd August 22, 2023
.Dt PROMPT-SORT 1
.Os
.Sh NAME
.Nm prompt-sort
.Nd sort a file interactively
.Sh SYNOPSIS
.Nm
.Op Fl n
.Op Ar file
.Sh DESCRIPTION
Sorts lines in
.Ar file
.Pq or standard input if not given
by presenting a series of choices to the user.
.Pp
The prompts are output on standard error so that
.Nm
may be used as part of a pipe, from an editor, etc.
.Pp
Options:
.Bl -tag -width Ds
.It Fl n
Number the output.
.It Fl t Ar count
Limit the ranking to the top
.Ar count
items.
This is more efficient than using
.Xr head 1
on the output
as it reduces the number of choices that must be made.
.El
.Sh EXIT STATUS
Returns 0 on success,
1 on error, or
.Dv EX_USAGE
.Pq 64
on usage error.
.Sh EXAMPLES
Raking a top-3 of games:
.Bd -literal -offset indent
$ prompt-sort -t3 -n games.txt
  1. ICO
  2. Zelda: The Minish Cap
choice? 1

  1. Zelda: The Minish Cap
  2. Shadow of the Colossus
choice? 2
\&...

  1. Death Stranding
  2. The Last of Us Part II
  3. Kirby's Return to Dream Land
.Ed
.Sh AUTHORS
.An Sijmen J. Mjulder
.Aq Mt ik@sjmulder.nl
